### ISSUE TITLE
Error: xxx/tmpSample.fa not found

### ISSUE THREAD

**Issue by ekaralashvili** [Dfam-consortium/RepeatModeler#236] opened 2024-03-07 12:36 UTC
I'm running RepeatModeler v4.1.5. and have an issue at the TRFMask stage. This is the error I get: 

Error: /share/pool/ek/project.phylogenomics.Lisa/2023_11_07_Andrenidae_genomes_ncbi/GCA_910592125.1_Andrena_haemorrhoa/GCA_910592125.1.fa.earlgrey/GCA_910592125.1_Andrena_haemorrhoa_EarlGrey/GCA_910592125.1_Andrena_haemorrhoa_RepeatModeler/RM_51078.ThuMar71009132024/tmpSample.fa not found

Giving directories simpler names seems to solve the issue, but I'm not sure what exactly in my paths is causing the problem?

**Comment by Lin-Yuying** [comment] 2024-03-18 04:21
Hi, 

I am using RepeatModeler version 2.0.5, and have the same problem. Have you solved it yet?

`-TRFMask: Could not open tmpSample.fa for reading!
   - TRFMask time 00:22:59 (hh:mm:ss) Elapsed Time
 -- Masking repeats from the previous rounds...
RepeatUtil::ncbiMaskDatabaseNativeMT(): Missing fastaFile parameter!`

Thanks in advance!

**Comment by rmhubley** [comment] 2024-06-18 20:26
I'm afraid I have no idea why the above path name would cause you issues.  It doesn't even say where the error occurred (e.g. what tool/line number).  I can't reproduce this so I am going to leave it open to see if anyone else reports something similar.  Or if you can still reproduce this we could look into it further.

**Comment by rmhubley** [comment] 2024-07-16 19:20
I am going to close this for now.  Let me know if you run into this again and can reproduce the error.

**Closed by rmhubley** 2024-07-16 19:20 UTC
Labels: bug

**Comment by leeyb9916** [comment] 2025-02-20 04:32
I used the RepeatModeler version.2.0.6 and I am getting the same error.

RepeatModeler Round # 2
========================
Searching for Repeats
 -- Sampling from the database...
   - Gathering up to 10000000 bp
   - Sequence extraction : 00:00:02 (hh:mm:ss) Elapsed Time
 -- Running TRFMask on the sequence...

Error: /Analysis_path/round-tmpSample.fa not found       1 Tandem Repeats Masked
