### ISSUE TITLE
LTRPipeline fails to execute MAFFT

### ISSUE THREAD

**Issue by marcopessoa** [Dfam-consortium/RepeatModeler#48] opened 2019-11-23 14:44 UTC
I got the following error during the LTRpipeline step:

```
LTR Structural Analysis
=======================
Running LtrHarvest...     : 00:09:31 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...  : 00:35:03 (hh:mm:ss) Elapsed Time
Aligning instances...sh: /bin/bin/mafft: No such file or directory
LTRPipeline: Error - could not produce a multiple alignment from the denovo LTR results.
LTRPipeline Time: 00:44:41 (hh:mm:ss) Elapsed Time
```

Even though the path for MAFFT was properly configured.

I found this line may be the culprit:

https://github.com/Dfam-consortium/RepeatModeler/blob/9c5d4bedc1764db11340e1766e83e60c03caa461/LTRPipeline#L543

Looks like the additional `/bin` will mess up with any configured path.

**Comment by jebrosen** [comment] 2019-11-23 19:10
The `configure` program and also `RepeatModeler` are supposed to be checking that `$binDir/bin/mafft` is executable long before trying to run it, so I am surprised it only fails then. I will try to reproduce this when I get a chance.

**Comment by marcopessoa** [comment] 2019-11-23 21:14
This reminds me, when running `configure`, it would not validate the path for `MAFFT`. I have the binary installed in `/bin`, and this line in `RepModelConfig.pm` already includes `bin/`, so it keeps looking for `/bin/bin/mafft`.

https://github.com/Dfam-consortium/RepeatModeler/blob/9c5d4bedc1764db11340e1766e83e60c03caa461/RepModelConfig.pm#L102

I had to modify this line to `'expected_binaries'    => [ 'mafft' ]` to make it work.

But again, when running the `LTRpipeline` above it looked for `/bin/bin/mafft` again and failed.

**Comment by jebrosen** [comment] 2019-11-23 21:24
Ah, so in your case the correct path for MAFFT would have been `/`.

> I had to modify this line to `'expected_binaries' => [ 'mafft' ]` to make it work.

That line only changed the files being checked for during validation, not the path `RepeatModeler` tries to run the programs from. Only the `'value'` lines were intended to be hand-edited.

@rmhubley - since MAFFT seems to be the only program that expects the additional `bin` subdirectory, maybe we can change that one in a future release?

**Comment by rmhubley** [comment] 2019-11-26 17:28
@marcopessoa -- I agree this is a bug.  I will get it fixed in the next update release.  In the meantime the workaround as Jeb indicated is to use "/" as your path.  Please let us know if this worked for you.

**Comment by jebrosen** [comment] 2020-03-11 18:11
This was fixed in 2.0.1 so that the mafft path is consistent with other paths and does not need an additional `bin` subdirectory.

**Closed by jebrosen** 2020-03-11 18:11 UTC

**Comment by artorias111** [comment] 2023-04-12 13:28
Hello! I recently ran RepeatModeler for a few assemlies and faced the same error. 
When I looked into `RepModelConfig.pm`, the lines were 'expected_binaries' => [ 'mafft' ]`. 

And this was the STDOUT from my RepeatModeler run. 

LTR Structural Analysis
=======================
Running LtrHarvest...     : 36:48:39 (hh:mm:ss) Elapsed Time
Running Ltr_retriever...  : 01:09:05 (hh:mm:ss) Elapsed Time
Aligning instances...LTRPipeline: Error - could not produce a multiple alignment from the denovo LTR results.
LTRPipeline Time: 37:57:56 (hh:mm:ss) Elapsed Time

Since the issue is fixed, I was wondering what went wrong. the MAFFT path seems to be intact. 
Any help would be appreciated, thanks!

**Comment by flaviabmedeiros** [comment] 2023-06-06 17:48
@artorias111 I am facing the same issue. I used a container, so I did not change configurations but now I'm concerned that the LTRPipeline represents a problem in my classified families.
